---
langs: [fr_FR, en_US]
baseurl: "/documentation" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- vendor
plugins:
- jekyll-paginate
- jekyll-seo-tag
title: "Documentations des plugins et widget de JAG"
description: "Ceci est la documentation des plugins et widgets créés par JAG de la solution domotique Jeedom."
author: "JAG"
image: https://doc.jeedom.com/img/logo.png
twitter:
  username: Jeedom_domotic
social:
  name: Jeedom
  links:
    - https://twitter.com/Jeedom_domotic
    - https://www.facebook.com/Jeedom-249936178537210/
    - https://github.com/jeedom
community: https://community.jeedom.com
market: https://market.jeedom.com
blog: https://blog.jeedom.com
doc: https://doc.jeedom.com
help: {{site.baseurl}}/help/